import React from "react";
import clsx from "clsx";
import type { Metadata } from "next";
import { Anton, Montserrat, Ubuntu } from "next/font/google";
import { navigations } from "@/shared/constants/navigation/navigations";
import Header from "@/shared/ui/header/header";
import "./globals.scss";

const anton = Anton({
  weight: "400",
  subsets: ["latin"],
  variable: "--app-anton",
});
const ubuntu = Ubuntu({
  weight: "500",
  subsets: ["latin", "cyrillic"],
  variable: "--app-ubuntu",
});
const montserrat = Montserrat({
  subsets: ["latin", "cyrillic"],
  variable: "--app-montserrat",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={clsx(montserrat.className, anton.variable, ubuntu.variable)}
      >
        <Header navigations={navigations} />
        {children}
      </body>
    </html>
  );
}
